# Worktree Context
# Generated: 2026-01-19T23:32:51+09:00

task_id: "unknown"
parent_agent: "orchestrator"
assigned_agent: "implementer"
branch: "feat/api-db-push-and-seed"
worktree_path: "/Users/matsuoka/ghq/github.com/matsuokah/vibecoding-repository-template/worktrees/feat-api-db-push-and-seed"

# Context references (to be filled by agent)
context:
  spec: ""
  plan: ""
  adr: ""

# Success criteria
success_criteria:
  - "contract test passes"
  - "docs updated if needed"

# Completion callback
on_complete:
  notify: "orchestrator"
  action: "report-status"
