# Worktree Context
# Generated: 2026-01-20T11:33:02+09:00

task_id: "unknown"
parent_agent: "orchestrator"
assigned_agent: "implementer"
branch: "fix/ci-failures"
worktree_path: "/Users/matsuoka/ghq/github.com/nahato-products/vibecoding-template-node-next/worktrees/fix-ci-failures"

# Context references (to be filled by agent)
context:
  spec: ""
  plan: ""
  adr: ""

# Success criteria
success_criteria:
  - "contract test passes"
  - "docs updated if needed"

# Completion callback
on_complete:
  notify: "orchestrator"
  action: "report-status"
